name: inteligenciaindustrialapp
description: GD&amp;T application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences:
  get_it:
  mobx:
  flutter_mobx:
  dio:
  connectivity:
  intl:
  mask_text_input_formatter:
  wakelock:
  vibrate:
  image:
  image_picker:
  camera:
  path_provider:
  path:
  json_annotation:
  flash:
  flutter_youtube: 2.0.0
  video_player: 0.10.11+1
  email_validator: 1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  build_runner:
  mobx_codegen:
  json_serializable:


flutter:

  uses-material-design: true

  assets:
    - assets/

    - assets/images/
    - assets/images/geometric/
    - assets/fonts/
    - assets/languages/
    - assets/videos/
